# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'Interests' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Moya/Core', '~> 14.0.0-alpha.1'

  # Pods for Interests

  target 'InterestsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
